### PR TITLE
Changed max-old-space-size to just below 4GB - Bring back 32bit arch support

### PR DESCRIPTION
**Pull request by sakowicz**
Dirty fix for https://github.com/tomayac/local-reverse-geocoder/issues/67

Disclaimer: I'm not a Node.js developer. I'm just facing the problem of https://github.com/tomayac/local-reverse-geocoder/issues/67 and deduced that this would be a fast solution for the problem.

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]
🚀

**Comment by tomayac** [comment]
No one shouted, so let's just go with the dirty fix for now. Fixes https://github.com/tomayac/local-reverse-geocoder/issues/67.

**Comment by tomayac** [comment]
Released `v0.15.1` that includes this fix. Thank you!

**Comment by tomayac** [comment]
Duh, you're right. Fixed now: https://unpkg.com/browse/local-reverse-geocoder@0.15.2/package.json

**Pull request merged**
