### PR TITLE
Add healthcheck services and support lazy loading the service

### PR DESCRIPTION
**Pull request by amirkarimi**
Adds both normal and deep healthcheck endpoints. This will be useful to recognize if the service is ready.

### CODE REVIEW

**Comment by tomayac** [comment]
Thanks, this looks great. My only nit is: can you use single quotes consistently everywhere?

**Comment by tomayac** [comment]
(Friendly ping)

**Comment by amirkarimi** [comment]
Oh sorry, I missed this. Will update it ASAP

**Comment by amirkarimi** [comment]
@tomayac Thanks for the comment. Updated.

**Comment by tomayac** [comment]
Merged. Thank you!

**Pull request merged**
