### PR TITLE
Use unzip-stream for in-memory unzip, and to avoid problems with node-unzip-2/fstream

### LINKED ISSUE #39: Crash when replacing yesterday's geodata (Extract.writer.error [Error: ENOENT: no such file or directory, lstat '/tmp/geonames/cities/cities1000.txt'])
### Reproduction steps:
1. Run `local-reverse-geocoder`, let it create files with dates in name (eg. `cities/cities1000_2021-03-19.txt`)
2. Wait another day (or rename file to older date, eg. `cities/cities1000_2021-03-19.txt` → `cities/cities1000_2021-03-15.txt`)
3. Start `local-reverse-geocoder` again.

### What I expected:
Geocoder updates its files.

### What actually happens
Geocoder crashes with `Extract.writer.error [Error: ENOENT: no such file or directory, lstat '/tmp/geonames/cities/cities1000.txt']`.

The cause is this:
- we call [unzip.Extract](https://github.com/tomayac/local-reverse-geocoder/blob/40f591edbfe138ff27251ebd2ed9304fdbb27ed2/index.js#L466)
- Extract extracts files from downloaded zip into a folder and emits [close](https://github.com/tomayac/local-reverse-geocoder/blob/40f591edbfe138ff27251ebd2ed9304fdbb27ed2/index.js#L467)
- We [rename](https://github.com/tomayac/local-reverse-geocoder/blob/40f591edbfe138ff27251ebd2ed9304fdbb27ed2/index.js#L468) and [unlink](https://github.com/tomayac/local-reverse-geocoder/blob/40f591edbfe138ff27251ebd2ed9304fdbb27ed2/index.js#L477)
- Extract uses `fstream` module, and it calls `stat` on extracted file *after calling close* - see [code](https://github.com/npm/fstream/blob/42354590e23bb514eb5c869eea64406be2947c6c/lib/writer.js#L269)!
- Calling `stat` on now nonexistent file causes crash (error is emitted from fstream, and not handled by anyone).

### Fix ideas:
1. Fix the underlying stream libs ([fstream](https://github.com/npm/fstream) shouldn't [touch the extracted file](https://github.com/npm/fstream/blob/42354590e23bb514eb5c869eea64406be2947c6c/lib/writer.js#L269) after it passes `close` event)
2. Ignore `error` event from `unzip.Extract`
```
extractStream
          .on('error', function (err) {
            if (err.code === 'ENOENT') {
              // ignore - fstream writer runs stat/lstat after extract is finished (and .close sent), and it crashes, because we have already used and moved/deleted it's file
            } else {
              throw err
            }
          })
```
3. Use unzip to extract just a single file we need, in memory, without writing to disk
4. Keep the extracted file (eg. cities1000.txt), so that we allow fstream to touch it however it wants after the extraction.

### Beware:
All `_get*data` methods have this problem, it needs to be fixed everywhere.

### PR DESCRIPTION
**Pull request by tkafka**
Replaced [problematic](https://github.com/tomayac/local-reverse-geocoder/issues/39) `node-unzip-2` for `unzip-stream`.

This way, we unzip a single required file directly from stream, with no temporary files on disk (and no problems with synchronization issues writing and reading them).

I also refactored a data downloading code to remove duplicate code paths.

Fixes #39

### CODE REVIEW

**Comment by tomayac** [comment]
Thank you! Looking at your fork, it seems like you made a couple more improvements that might be worth pulling over here.

**Comment by tomayac** [comment]
Just released v0.10.0 that contains these changes. Thanks again for the contribution. I have added your name to the acknowledgments :-)

**Comment by tkafka** [comment]
Awesome, thanks!

**Comment by tkafka** [comment]
I deprected the `local-reverse-geocoder-2` fork.

**Pull request merged**
